# 服务器基础配置
# 包含服务器名称、简介和虚拟在线人数显示。

[server]
# 服务器显示名称，会用于列表与部分提示信息。
name = "[#F285D1]镜[#F285E3]像[#E59AFF]物[#CC99FF]语"
# 服务器简介文本。
desc = "基于 Go mdt-server服务器 重构了原本的服务端使用了 QQ群333641130 服务器依然是demo版本 如果你看到了说明在测试"
# 虚拟在线人数，会叠加到展示人数中。
virtual_players = 0
