; API 配置
; API key 必须符合格式：
; mdt-server-go-xxxxxxxxxxxxxxx-xxxxxxxxxxxxx-xxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxx-yzf-xxxxxxxxxx
; 只能使用小写字母和数字 否则将报API。

[api]
enabled = 1
bind = 0.0.0.0:8090
key =
keys =

