; mdt-server main config (INI)

[config]
api_file = api.ini
conn_uuid_auto_create = 1
player_identity_auto_create = 1
public_conn_uuid_enabled = 1
public_conn_uuid_file = json/conn_uuid.json
reload_interval_sec = 5
reload_log_enabled = 0
translated_conn_log_enabled = 1

[building]
log_enabled = 1
translated_enabled = 1
