; misc settings

[data]
database_enabled = 0
directory = data\events
dsn = 
mode = file

[paths]
assets_dir = assets
logs_dir = logs
worlds_dir = assets\worlds

[mods]
directory = mods
enabled = 0
go_dir = mods\go
java_home = 
js_dir = mods\js
node_dir = mods\node

[persist]
directory = data\state
enabled = 1
file = server-state.json
interval_sec = 30
msav_dir = data\snapshots
msav_file = 
save_msav = 1

[script]
daily_gc_time = 
file = data\state\scripts.json

[admin]
ops_file = data\state\ops.json
