; name 服务器名称
; desc 服务器简介
; virtual_players 虚拟玩家数量可自定义 0代表没有玩家 xxx任意数字代表有玩家即是数量 新玩家添加后会在数量+1
[server]
name = go-mdt-server
desc = 基于 Go mdt-server服务器 重构了原本的服务端使用了 QQ群333641130 demo版本 在测试
virtual_players = 0 

