$defaultCsv = "C:\Users\43551\Desktop\mdt-server\Mindustry-master\go-server\docs\remote-methods.csv"
$csvPath = if ($env:CSVPATH -and $env:CSVPATH.Trim().Length -gt 0) { $env:CSVPATH } else { $defaultCsv }
$defaultOut = "C:\Users\43551\Desktop\mdt-server\Mindustry-master\go-server\internal\protocol\remote_packets.go"
$outPath = if ($env:OUTPATH -and $env:OUTPATH.Trim().Length -gt 0) { $env:OUTPATH } else { $defaultOut }

if (!(Test-Path $csvPath)) {
    Write-Error "missing csv: $csvPath"
    exit 1
}

$rows = Import-Csv $csvPath

function Map-Type($t) {
    $t = Normalize-Type $t
    switch ($t) {
        "int" { return "int32" }
        "short" { return "int16" }
        "byte" { return "int8" }
        "byte[]" { return "[]byte" }
        "long" { return "int64" }
        "float" { return "float32" }
        "double" { return "float64" }
        "boolean" { return "bool" }
        "String" { return "string" }
        "int[]" { return "[]int32" }
        "String[]" { return "[]string" }
        "String[][]" { return "[][]string" }
        "Object" { return "any" }
        "Content" { return "Content" }
        "IntSeq" { return "IntSeq" }
        "ItemStack[]" { return "[]ItemStack" }
        "LiquidStack[]" { return "[]LiquidStack" }
        "AdminAction" { return "AdminAction" }
        "KickReason" { return "KickReason" }
        "LMarkerControl" { return "LMarkerControl" }
        "Rules" { return "Rules" }
        "MapObjectives" { return "MapObjectives" }
        "ObjectiveMarker" { return "ObjectiveMarker" }
        "TraceInfo" { return "TraceInfo" }
        "Team" { return "Team" }
        "Unit" { return "Unit" }
        "Building" { return "Building" }
        "Vec2" { return "Vec2" }
        "Point2" { return "Point2" }
        "Color" { return "Color" }
        "Block" { return "Block" }
        "Item" { return "Item" }
        "Liquid" { return "Liquid" }
        "UnitType" { return "UnitType" }
        "BulletType" { return "BulletType" }
        "StatusEffect" { return "StatusEffect" }
        "Effect" { return "Effect" }
        "Weather" { return "Weather" }
        "Sound" { return "Sound" }
        "Tile" { return "Tile" }
        "Player" { return "Entity" }
        "Itemsc" { return "Entity" }
        "UnitCommand" { return "*UnitCommand" }
        "UnitStance" { return "UnitStance" }
        "UnitSyncContainer" { return "UnitSyncContainer" }
        "Queue<BuildPlan>" { return "[]*BuildPlan" }
        default { return "any" }
    }
}

function Normalize-Type($t) {
    $t = $t.Trim()
    $t = $t -replace "^@Nullable\\s+", ""
    $t = $t -replace "^final\\s+", ""
    $suffix = ""
    while ($t.EndsWith("[]")) {
        $suffix += "[]"
        $t = $t.Substring(0, $t.Length - 2)
    }
    $parts = $t -split '\\.'
    $base = $parts[$parts.Length - 1]
    return $base + $suffix
}

function Clean-Name($name) {
    $n = $name -replace '[^a-zA-Z0-9_]', '_'
    if ($n -match '^[0-9]') { $n = "_" + $n }
    return $n
}

function Split-Param($p) {
    $parts = ($p.Trim() -split '\s+')
    if ($parts.Length -lt 2) { return $null }
    $name = $parts[$parts.Length - 1]
    $type = ($parts[0..($parts.Length - 2)] -join ' ')
    return @($type, $name)
}

$out = New-Object System.Collections.Generic.List[string]
$defs = New-Object System.Collections.Generic.List[string]
$out.Add("package protocol")
$out.Add("")
$out.Add("// Code generated by tools/remote_gen/gen.ps1; DO NOT EDIT.")
$out.Add("// These packets map @Remote methods. Read/Write are TODO stubs.")
$out.Add("")

$out.Add("func remotePacketFactories() []PacketFactory {")
$out.Add("    return []PacketFactory{")

$idx = 0
foreach ($row in $rows) {
    $sig = $row.signature
    if ($sig -notmatch "void") { continue }
    $sig = $sig -replace "\{", ""
    $sig = $sig -replace ";", ""

    if ($sig -match "void\s+([a-zA-Z0-9_]+)\s*\((.*)\)") {
        $method = $Matches[1]
        $params = $Matches[2]
        $remote = $row.remote
        $calledServer = $remote -match "called\s*=\s*Loc\.server"
        $calledClient = $remote -match "called\s*=\s*Loc\.client"
        $calledBoth = $remote -match "called\s*=\s*Loc\.both"
        if (-not ($calledServer -or $calledClient -or $calledBoth)) {
            # default called location when not specified
            $calledServer = $true
        }
        $file = Split-Path $row.file -Leaf
        $class = $file -replace ".java",""
        $typeName = "Remote_" + (Clean-Name $class) + "_" + (Clean-Name $method) + "_" + $idx
        $out.Add("        func() Packet { return &" + $typeName + "{} },")

        $defs.Add("")
        $defs.Add("type " + $typeName + " struct {")
        if ($params.Trim().Length -gt 0) {
            $plist = $params.Split(",")
            $pidx = 0
            foreach ($p in $plist) {
                if (-not $calledServer -and $pidx -eq 0) {
                    $pidx++
                    continue
                }
                $pclean = $p.Trim()
                $split = Split-Param $pclean
                if ($split -ne $null) {
                    $pt = $split[0]
                    $pn = $split[1]
                    $goType = Map-Type $pt
                    $field = Clean-Name ($pn.Substring(0,1).ToUpper() + $pn.Substring(1))
                    $defs.Add("    " + $field + " " + $goType)
                } else {
                    $defs.Add("    Param" + $pidx + " any")
                }
                $pidx++
            }
        }
        $defs.Add("}")
        $defs.Add("")
        $defs.Add("func (p *" + $typeName + ") Read(r *Reader, _ int) error {")
        if ($params.Trim().Length -gt 0) {
            $plist = $params.Split(",")
            $pidx = 0
            foreach ($p in $plist) {
                if (-not $calledServer -and $pidx -eq 0) {
                    $pidx++
                    continue
                }
                $pclean = $p.Trim()
                $split = Split-Param $pclean
                if ($split -ne $null) {
                    $pt = $split[0]
                    $pn = $split[1]
                    $field = Clean-Name ($pn.Substring(0,1).ToUpper() + $pn.Substring(1))
                    switch (Map-Type $pt) {
                        "int32" { $defs.Add("    if v, err := r.ReadInt32(); err != nil { return err } else { p.$field = v }") }
                        "int16" { $defs.Add("    if v, err := r.ReadInt16(); err != nil { return err } else { p.$field = v }") }
                        "int8" { $defs.Add("    if v, err := r.ReadByte(); err != nil { return err } else { p.$field = int8(v) }") }
                        "int64" { $defs.Add("    if v, err := r.ReadInt64(); err != nil { return err } else { p.$field = v }") }
                        "float32" { $defs.Add("    if v, err := r.ReadFloat32(); err != nil { return err } else { p.$field = v }") }
                        "float64" { $defs.Add("    if v, err := r.ReadFloat64(); err != nil { return err } else { p.$field = v }") }
                        "bool" { $defs.Add("    if v, err := r.ReadBool(); err != nil { return err } else { p.$field = v }") }
                        "string" { $defs.Add("    if v, err := ReadString(r); err != nil { return err } else if v != nil { p.$field = *v }") }
                        "[]byte" { $defs.Add("    if v, err := ReadBytes(r); err != nil { return err } else { p.$field = v }") }
                        "[][]string" { $defs.Add("    if v, err := ReadStringArray(r); err != nil { return err } else { p.$field = v }") }
                        "any" { $defs.Add("    if v, err := ReadObject(r, false, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Content" { $defs.Add("    if v, err := ReadContent(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "IntSeq" { $defs.Add("    if v, err := ReadIntSeq(r); err != nil { return err } else { p.$field = v }") }
                        "[]ItemStack" { $defs.Add("    if v, err := ReadItemStacks(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "[]LiquidStack" { $defs.Add("    if v, err := ReadLiquidStacks(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "[]*BuildPlan" { $defs.Add("    if v, err := ReadPlansQueue(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "AdminAction" { $defs.Add("    if v, err := ReadAction(r); err != nil { return err } else { p.$field = v }") }
                        "KickReason" { $defs.Add("    if v, err := ReadKick(r); err != nil { return err } else { p.$field = v }") }
                        "LMarkerControl" { $defs.Add("    if v, err := ReadMarkerControl(r); err != nil { return err } else { p.$field = v }") }
                        "Rules" { $defs.Add("    if v, err := ReadRules(r); err != nil { return err } else { p.$field = v }") }
                        "MapObjectives" { $defs.Add("    if v, err := ReadObjectives(r); err != nil { return err } else { p.$field = v }") }
                        "ObjectiveMarker" { $defs.Add("    if v, err := ReadObjectiveMarker(r); err != nil { return err } else { p.$field = v }") }
                        "TraceInfo" { $defs.Add("    if v, err := ReadTraceInfo(r); err != nil { return err } else { p.$field = v }") }
                        "Entity" { $defs.Add("    if v, err := ReadEntity(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "*UnitCommand" { $defs.Add("    if v, err := ReadCommand(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "UnitStance" { $defs.Add("    if v, err := ReadStance(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "UnitSyncContainer" { $defs.Add("    if v, err := ReadUnitContainerBox(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Team" { $defs.Add("    if v, err := ReadTeam(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Unit" { $defs.Add("    if v, err := ReadUnit(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Building" { $defs.Add("    if v, err := ReadBuilding(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Vec2" { $defs.Add("    if v, err := ReadVec2(r); err != nil { return err } else { p.$field = v }") }
                        "Point2" { $defs.Add("    if v, err := ReadPoint2(r); err != nil { return err } else { p.$field = v }") }
                        "Color" { $defs.Add("    if v, err := ReadColor(r); err != nil { return err } else { p.$field = v }") }
                        "Block" { $defs.Add("    if v, err := ReadBlock(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Item" { $defs.Add("    if v, err := ReadItem(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Liquid" { $defs.Add("    if v, err := ReadLiquid(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "UnitType" { $defs.Add("    if v, err := ReadUnitType(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "BulletType" { $defs.Add("    if v, err := ReadBulletType(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "StatusEffect" { $defs.Add("    if v, err := ReadStatusEffect(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Effect" { $defs.Add("    if v, err := ReadEffect(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Weather" { $defs.Add("    if v, err := ReadWeather(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Sound" { $defs.Add("    if v, err := ReadSound(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "Tile" { $defs.Add("    if v, err := ReadTile(r, r.Ctx); err != nil { return err } else { p.$field = v }") }
                        "[]int32" { $defs.Add("    if v, err := ReadInts(r); err != nil { return err } else { p.$field = v }") }
                        "[]string" { $defs.Add("    if v, err := ReadStrings(r); err != nil { return err } else { p.$field = v }") }
                        default { $defs.Add("    return ErrUnsupportedTypeIO") }
                    }
                }
                $pidx++
            }
        }
        $defs.Add("    return nil")
        $defs.Add("}")
        $defs.Add("")
        $defs.Add("func (p *" + $typeName + ") Write(w *Writer) error {")
        if ($params.Trim().Length -gt 0) {
            $plist = $params.Split(",")
            $pidx = 0
            foreach ($p in $plist) {
                if (-not $calledServer -and $pidx -eq 0) {
                    $pidx++
                    continue
                }
                $pclean = $p.Trim()
                $split = Split-Param $pclean
                if ($split -ne $null) {
                    $pt = $split[0]
                    $pn = $split[1]
                    $field = Clean-Name ($pn.Substring(0,1).ToUpper() + $pn.Substring(1))
                    switch (Map-Type $pt) {
                        "int32" { $defs.Add("    if err := w.WriteInt32(p.$field); err != nil { return err }") }
                        "int16" { $defs.Add("    if err := w.WriteInt16(p.$field); err != nil { return err }") }
                        "int8" { $defs.Add("    if err := w.WriteByte(byte(p.$field)); err != nil { return err }") }
                        "int64" { $defs.Add("    if err := w.WriteInt64(p.$field); err != nil { return err }") }
                        "float32" { $defs.Add("    if err := w.WriteFloat32(p.$field); err != nil { return err }") }
                        "float64" { $defs.Add("    if err := w.WriteFloat64(p.$field); err != nil { return err }") }
                        "bool" { $defs.Add("    if err := w.WriteBool(p.$field); err != nil { return err }") }
                        "string" { $sv = "s" + $pidx; $defs.Add("    " + $sv + " := p.$field; if err := WriteString(w, &" + $sv + "); err != nil { return err }") }
                        "[]byte" { $defs.Add("    if err := WriteBytes(w, p.$field); err != nil { return err }") }
                        "[][]string" { $defs.Add("    if err := WriteStringArray(w, p.$field); err != nil { return err }") }
                        "any" { $defs.Add("    if err := WriteObject(w, p.$field, w.Ctx); err != nil { return err }") }
                        "Content" { $defs.Add("    if err := WriteContent(w, p.$field); err != nil { return err }") }
                        "IntSeq" { $defs.Add("    if err := WriteIntSeq(w, p.$field); err != nil { return err }") }
                        "[]ItemStack" { $defs.Add("    if err := WriteItemStacks(w, p.$field); err != nil { return err }") }
                        "[]LiquidStack" { $defs.Add("    if err := WriteLiquidStacks(w, p.$field); err != nil { return err }") }
                        "[]*BuildPlan" { $defs.Add("    if err := WritePlansQueueNet(w, p.$field, w.Ctx); err != nil { return err }") }
                        "AdminAction" { $defs.Add("    if err := WriteAction(w, p.$field); err != nil { return err }") }
                        "KickReason" { $defs.Add("    if err := WriteKick(w, p.$field); err != nil { return err }") }
                        "LMarkerControl" { $defs.Add("    if err := WriteMarkerControl(w, p.$field); err != nil { return err }") }
                        "Rules" { $defs.Add("    if err := WriteRules(w, p.$field); err != nil { return err }") }
                        "MapObjectives" { $defs.Add("    if err := WriteObjectives(w, p.$field); err != nil { return err }") }
                        "ObjectiveMarker" { $defs.Add("    if err := WriteObjectiveMarker(w, p.$field); err != nil { return err }") }
                        "TraceInfo" { $defs.Add("    if err := WriteTraceInfo(w, p.$field); err != nil { return err }") }
                        "Entity" { $defs.Add("    if err := WriteEntity(w, p.$field); err != nil { return err }") }
                        "*UnitCommand" { $defs.Add("    if err := WriteCommand(w, p.$field); err != nil { return err }") }
                        "UnitStance" { $defs.Add("    if err := WriteStance(w, &p.$field); err != nil { return err }") }
                        "UnitSyncContainer" { $defs.Add("    if err := WriteUnitContainer(w, p.$field); err != nil { return err }") }
                        "Team" { $defs.Add("    if err := WriteTeam(w, &p.$field); err != nil { return err }") }
                        "Unit" { $defs.Add("    if err := WriteUnit(w, p.$field); err != nil { return err }") }
                        "Building" { $defs.Add("    if err := WriteBuilding(w, p.$field); err != nil { return err }") }
                        "Vec2" { $defs.Add("    if err := WriteVec2(w, p.$field); err != nil { return err }") }
                        "Point2" { $defs.Add("    if err := WritePoint2(w, p.$field); err != nil { return err }") }
                        "Color" { $defs.Add("    if err := WriteColor(w, p.$field); err != nil { return err }") }
                        "Block" { $defs.Add("    if err := WriteBlock(w, p.$field); err != nil { return err }") }
                        "Item" { $defs.Add("    if err := WriteItem(w, p.$field); err != nil { return err }") }
                        "Liquid" { $defs.Add("    if err := WriteLiquid(w, p.$field); err != nil { return err }") }
                        "UnitType" { $defs.Add("    if err := WriteUnitType(w, p.$field); err != nil { return err }") }
                        "BulletType" { $defs.Add("    if err := WriteBulletType(w, p.$field); err != nil { return err }") }
                        "StatusEffect" { $defs.Add("    if err := WriteStatusEffect(w, p.$field); err != nil { return err }") }
                        "Effect" { $defs.Add("    if err := WriteEffect(w, p.$field); err != nil { return err }") }
                        "Weather" { $defs.Add("    if err := WriteWeather(w, p.$field); err != nil { return err }") }
                        "Sound" { $defs.Add("    if err := WriteSound(w, p.$field); err != nil { return err }") }
                        "Tile" { $defs.Add("    if err := WriteTile(w, p.$field); err != nil { return err }") }
                        "[]int32" { $defs.Add("    if err := WriteInts(w, p.$field); err != nil { return err }") }
                        "[]string" { $defs.Add("    if err := WriteStrings(w, p.$field, 0); err != nil { return err }") }
                        default { $defs.Add("    return ErrUnsupportedTypeIO") }
                    }
                }
                $pidx++
            }
        }
        $defs.Add("    return nil")
        $defs.Add("}")
        $defs.Add("")
        $prio = "PriorityNormal"
        if ($remote -match "priority\\s*=\\s*PacketPriority\\.high") { $prio = "PriorityHigh" }
        if ($remote -match "priority\\s*=\\s*PacketPriority\\.low") { $prio = "PriorityLow" }
        $defs.Add("func (p *" + $typeName + ") Priority() int { return " + $prio + " }")
        $defs.Add("")
        $idx++
    }
}

$out.Add("    }")
$out.Add("}")
$out.Add("")
$out.AddRange($defs)
$out.Add("")
$out.Add("func initRemotePackets(r *PacketRegistry) {")
$out.Add("    for _, f := range remotePacketFactories() {")
$out.Add("        r.Register(f)")
$out.Add("    }")
$out.Add("}")

[System.IO.File]::WriteAllLines($outPath, $out, [System.Text.Encoding]::UTF8)
Write-Host ("generated " + $idx + " remote packet stubs to " + $outPath)
